[build]
  command = "npm ci && npm run build"
  publish = "build"

[build.environment]
  NODE_OPTIONS = "--no-corepack"
  NPM_VERSION = "10.9.2"

[context.production.environment]
  NODE_ENV = "production"
